#!/usr/bin/env bash

file1="/usr/lib/slack/resources/app.asar.unpacked/src/static/index.js"
file2="/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js"

test_file() {
	if [[ ! -w "${1}" ]]; then
	  echo "Cannot write to ${1}"
	  exit 1
	fi
}

patch_file() {
	if grep -q "slack-black-theme" "${1}"; then
	  echo "Already patched"
	  return
	fi

	cp ${1} ${1}.orig

	cat >> ${1} << '_EOF'

document.addEventListener('DOMContentLoaded', function() {
 $.ajax({
   url: 'https://cdn.rawgit.com/widget-/slack-black-theme/master/custom.css',
   success: function(css) {
     \$("<style></style>").appendTo('head').html(css);
   }
 });
});

_EOF
}

test_file "${file1}"
test_file "${file2}"


patch_file "${file1}"
patch_file "${file2}"

exit 0

